"""Schemas Pydantic do projeto"""

from app.schemas.event import (
    UserLocation,
    EventSearchFilters,
    EventCreate,
    EventRead,
    EventResponse,
    EventSearchResponse,
    JoinEventRequest,
    EventParticipantRead,
    JoinEventResponse,
    SuggestedPlayerRead,
    EventSuggestionsResponse,
    PersonalizedFeedItem,
    PersonalizedFeedResponse,
)
from app.schemas.club import (
    ClubCreate,
    ClubRead,
    ClubResponse,
    ClubNearbyResponse,
    ClubJoinRequest,
    ClubMemberRead,
    ClubJoinResponse,
    ClubMembershipReviewRequest,
    ClubMembershipReviewResponse,
    TeamSynergyCardRead,
    TeamSynergyCardResponse,
)
from app.schemas.notification import NotificationRead, NotificationListResponse
from app.schemas.athlete import AthleteCreate, AthleteResponse
from app.schemas.ranked import RankedUserRead, RankedUsersResponse, UserRankRead, UserRankResponse
from app.schemas.chat import ChatMessageCreate, ChatMessageRead, ChatRoomRead, ChatRoomResponse, ChatMessageResponse
from app.schemas.court import CourtCreate, CourtRead, CourtResponse, BookingCreate, BookingRead, BookingResponse
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserRead,
    UserResponse,
    UserListResponse,
    UserDeleteResponse,
    UserDeleteData,
    UserInterestBase,
    UserInterestCreate,
    UserInterestRead,
    PlayerStatsBase,
    PlayerStatsUpdate,
    PlayerStatsRead,
    PlayerStatsResponse,
    UserProfileCard,
    UserProfileResponse,
)

__all__ = [
    "UserLocation",
    "EventSearchFilters",
    "EventCreate",
    "EventRead",
    "EventResponse",
    "EventSearchResponse",
    "JoinEventRequest",
    "EventParticipantRead",
    "JoinEventResponse",
    "SuggestedPlayerRead",
    "EventSuggestionsResponse",
    "PersonalizedFeedItem",
    "PersonalizedFeedResponse",
    "ClubCreate",
    "ClubRead",
    "ClubResponse",
    "ClubNearbyResponse",
    "ClubJoinRequest",
    "ClubMemberRead",
    "ClubJoinResponse",
    "ClubMembershipReviewRequest",
    "ClubMembershipReviewResponse",
    "TeamSynergyCardRead",
    "TeamSynergyCardResponse",
    "NotificationRead",
    "NotificationListResponse",
    "AthleteCreate",
    "AthleteResponse",
    "UserRankRead",
    "UserRankResponse",
    "RankedUserRead",
    "RankedUsersResponse",
    "ChatMessageCreate",
    "ChatMessageRead",
    "ChatRoomRead",
    "ChatRoomResponse",
    "ChatMessageResponse",
    "CourtCreate",
    "CourtRead",
    "CourtResponse",
    "BookingCreate",
    "BookingRead",
    "BookingResponse",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserRead",
    "UserResponse",
    "UserListResponse",
    "UserDeleteResponse",
    "UserDeleteData",
    "UserInterestBase",
    "UserInterestCreate",
    "UserInterestRead",
    "PlayerStatsBase",
    "PlayerStatsUpdate",
    "PlayerStatsRead",
    "PlayerStatsResponse",
    "UserProfileCard",
    "UserProfileResponse",
]
