"""Constantes compartilhadas de progressão de XP."""

from __future__ import annotations

ALL_PROGRESS_ATTRIBUTES: tuple[str, ...] = (
    "pace",
    "shooting",
    "passing",
    "defense",
    "physical",
    "technique",
    "short_finish",
    "long_shot",
    "heading",
    "free_kick",
    "short_pass",
    "long_pass",
    "crossing",
    "dribbling",
    "ball_shielding",
    "sprint",
    "acceleration",
    "stamina",
    "tackle",
    "interception",
    "marking",
    "reflexes",
    "elasticity",
    "box_presence",
    "distribution",
    "spike_power",
    "spike_accuracy",
    "serve_power",
    "serve_tactical",
    "reception",
    "floor_defense",
    "coverage",
    "setting",
    "creativity",
    "game_vision",
    "lateral_agility",
    "reaction",
    "coordination",
    "sand_agility",
    "jumping_endurance",
    "shoot_long",
    "shoot_mid",
    "shoot_short",
    "finishing",
    "velocity",
    "jump",
    "agility",
    "energy",
    "strength",
    "balance",
    "ball_control",
    "vision",
    "dribble",
    "steal",
    "block",
    "perim_def",
    "post_def",
    "rebound",
    "reb_predict",
    "combativeness",
)

ALL_PROGRESS_ATTRIBUTES = tuple(dict.fromkeys(ALL_PROGRESS_ATTRIBUTES))
