// Mocks generated by Mockito 5.4.6 from annotations
// in matching_esportivo_mobile/test/data/services/match_list_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:matching_esportivo_mobile/data/models/court.dart' as _i3;
import 'package:matching_esportivo_mobile/data/models/player_stats.dart' as _i2;
import 'package:matching_esportivo_mobile/data/services/api_service.dart'
    as _i4;
import 'package:matching_esportivo_mobile/data/services/local_storage_service.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlayerStats_0 extends _i1.SmartFake implements _i2.PlayerStats {
  _FakePlayerStats_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerStatsResponse_1 extends _i1.SmartFake
    implements _i2.PlayerStatsResponse {
  _FakePlayerStatsResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCourtsResponse_2 extends _i1.SmartFake
    implements _i3.CourtsResponse {
  _FakeCourtsResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCourt_3 extends _i1.SmartFake implements _i3.Court {
  _FakeCourt_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PlayerStats> getPlayerStats(String? playerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayerStats,
          [playerId],
        ),
        returnValue: _i5.Future<_i2.PlayerStats>.value(_FakePlayerStats_0(
          this,
          Invocation.method(
            #getPlayerStats,
            [playerId],
          ),
        )),
      ) as _i5.Future<_i2.PlayerStats>);

  @override
  _i5.Future<_i2.PlayerStatsResponse> getAllPlayerStats() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPlayerStats,
          [],
        ),
        returnValue: _i5.Future<_i2.PlayerStatsResponse>.value(
            _FakePlayerStatsResponse_1(
          this,
          Invocation.method(
            #getAllPlayerStats,
            [],
          ),
        )),
      ) as _i5.Future<_i2.PlayerStatsResponse>);

  @override
  _i5.Future<_i2.PlayerStats> updatePlayerStats(
    String? playerId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlayerStats,
          [
            playerId,
            updates,
          ],
        ),
        returnValue: _i5.Future<_i2.PlayerStats>.value(_FakePlayerStats_0(
          this,
          Invocation.method(
            #updatePlayerStats,
            [
              playerId,
              updates,
            ],
          ),
        )),
      ) as _i5.Future<_i2.PlayerStats>);

  @override
  _i5.Future<_i3.CourtsResponse> getAvailableCourts({
    double? latitude,
    double? longitude,
    String? sport,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableCourts,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #sport: sport,
          },
        ),
        returnValue: _i5.Future<_i3.CourtsResponse>.value(_FakeCourtsResponse_2(
          this,
          Invocation.method(
            #getAvailableCourts,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
              #sport: sport,
            },
          ),
        )),
      ) as _i5.Future<_i3.CourtsResponse>);

  @override
  _i5.Future<_i3.Court> getCourtDetails(String? courtId) => (super.noSuchMethod(
        Invocation.method(
          #getCourtDetails,
          [courtId],
        ),
        returnValue: _i5.Future<_i3.Court>.value(_FakeCourt_3(
          this,
          Invocation.method(
            #getCourtDetails,
            [courtId],
          ),
        )),
      ) as _i5.Future<_i3.Court>);

  @override
  _i5.Future<_i3.Court> updateCourtSlots(
    String? courtId,
    int? availableSlots,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCourtSlots,
          [
            courtId,
            availableSlots,
          ],
        ),
        returnValue: _i5.Future<_i3.Court>.value(_FakeCourt_3(
          this,
          Invocation.method(
            #updateCourtSlots,
            [
              courtId,
              availableSlots,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Court>);

  @override
  _i5.Future<Map<String, dynamic>> get(String? path) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> post(
    String? path, {
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {#data: data},
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> patch(
    String? path, {
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {#data: data},
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i6.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> savePlayerStats(List<_i2.PlayerStats>? stats) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePlayerStats,
          [stats],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.PlayerStats>> getPlayerStats() => (super.noSuchMethod(
        Invocation.method(
          #getPlayerStats,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.PlayerStats>>.value(<_i2.PlayerStats>[]),
      ) as _i5.Future<List<_i2.PlayerStats>>);

  @override
  _i5.Future<void> clearPlayerStats() => (super.noSuchMethod(
        Invocation.method(
          #clearPlayerStats,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveCourts(List<_i3.Court>? courts) => (super.noSuchMethod(
        Invocation.method(
          #saveCourts,
          [courts],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Court>> getCourts() => (super.noSuchMethod(
        Invocation.method(
          #getCourts,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Court>>.value(<_i3.Court>[]),
      ) as _i5.Future<List<_i3.Court>>);

  @override
  _i5.Future<void> clearCourts() => (super.noSuchMethod(
        Invocation.method(
          #clearCourts,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveUserProfile(Map<String, dynamic>? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [profile],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> clearUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #clearUserProfile,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveMatchState(Map<String, dynamic>? matchState) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMatchState,
          [matchState],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getMatchState() => (super.noSuchMethod(
        Invocation.method(
          #getMatchState,
          [],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> clearMatchState() => (super.noSuchMethod(
        Invocation.method(
          #clearMatchState,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addToRecentCourts(_i3.Court? court) => (super.noSuchMethod(
        Invocation.method(
          #addToRecentCourts,
          [court],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Court>> getRecentCourts() => (super.noSuchMethod(
        Invocation.method(
          #getRecentCourts,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Court>>.value(<_i3.Court>[]),
      ) as _i5.Future<List<_i3.Court>>);

  @override
  _i5.Future<void> clearRecentCourts() => (super.noSuchMethod(
        Invocation.method(
          #clearRecentCourts,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  int getMinutesSinceLastSync() => (super.noSuchMethod(
        Invocation.method(
          #getMinutesSinceLastSync,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool isCacheExpired({int? expireAfterMinutes = 30}) => (super.noSuchMethod(
        Invocation.method(
          #isCacheExpired,
          [],
          {#expireAfterMinutes: expireAfterMinutes},
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> loadString(String? key) => (super.noSuchMethod(
        Invocation.method(
          #loadString,
          [key],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> saveJson(
    String? key,
    Map<String, dynamic>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveJson,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> loadJson(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadJson,
          [key],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> hasKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #hasKey,
          [key],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> saveInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int?> loadInt(String? key) => (super.noSuchMethod(
        Invocation.method(
          #loadInt,
          [key],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<void> saveBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool?> loadBool(String? key) => (super.noSuchMethod(
        Invocation.method(
          #loadBool,
          [key],
        ),
        returnValue: _i5.Future<bool?>.value(),
      ) as _i5.Future<bool?>);

  @override
  _i5.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
